services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - ./.db:/var/lib/postgresql/data
    restart: always
